name: expense_tracker
description: A Flutter app for tracking expenses.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4
  flutter_secure_storage:
    path: ./local_plugins/flutter_secure_storage
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ./assets/images/
    - ./assets/icons/
    - .env
